[[rule]]
devices = ["FP3", "FP4"]
categories = ["secure-boot", "bfu-secure", "afu-secure"]
class = "no"
conclusion = "Insecure defaults"
reference = "https://forum.fairphone.com/t/bootloader-avb-keys-used-in-roms-for-fairphone-3-4/83448/11"

[[rule]]
devices = ["FP5"]
categories = ["secure-boot"]
class = "yes"
conclusion = "Yes"
